grails-app/controllers/org/munaylab/lotengo/GestionController.groovy
package org.munaylab.lotengo

class GestionController {

    def gestionService

    def index() {}

    def actualizarUbicacion(Ubicacion command) {
        Ubicacion ubicacion = gestionService.actualizarUbicacion(command)
        if (ubicacion.hasErrors()) {
            flash.result = [tipo: 'danger', texto: command.errors.allErrors]
        }
        redirect uri:'/'
    }
    def eliminarUbicacion(Ubicacion command) {
        command.delete()
    }
    def listarUbicaciones() {
        [ubicaciones: Ubicacion.listOrderByProvincia()]
    }

    def actualizarPaquete(Paquete command) {
        Paquete paquete = gestionService.actualizarPaquete(command)
        if (paquete.hasErrors()) {
            flash.result = [tipo: 'danger', texto: command.errors.allErrors]
        }
        redirect uri:'/'
    }
    def listarPaquetes() {
        [paquetes: Paquete.listOrderByCaja()]
    }
    def buscarPaquete() {
        def result = gestionService.buscarPaquete(params.long('caja'))
        if (result && result.paquete) {
            flash.encontrado = result
        } else {
            flash.result = [tipo: 'danger', texto: 'No se encontró resultado del paquete solicitado.']
        }
        redirect uri: '/'
    }

    def enviar(Long id) {
        Historial enviado = gestionService.paqueteEnviado(id)
        if (enviado) {
            flash.result = [tipo: 'info', texto: "Se cambió el estado del paquete ${enviado.paquete.caja} a ENVIADO"]
        } else {
            flash.result = [tipo: 'danger', texto: 'Ocurrió un problema al cambiar el estado del paquete.']
        }
        redirect uri:'/'
    }

    def recibido(Long id) {
        Date fecha = params.fecha ? new Date().parse('dd/MM/yyyy', params.fecha) : new Date()
        Historial recibido = gestionService.paqueteRecibido(id, params.observacion, fecha)
        if (recibido) {
            flash.result = [tipo: 'info', texto: "Se cambió el estado del paquete ${recibido.paquete.caja} a RECIBIDO"]
        } else {
            flash.result = [tipo: 'error', texto: 'Ocurrió un problema al cambiar el estado del paquete.']
        }
        redirect uri:'/'
    }

    def perdido(Long id) {
        Historial perdido = gestionService.paquetePerdido(id)
        if (perdido) {
            flash.result = [tipo: 'info', texto: "Se cambió el estado del paquete ${perdido.paquete.caja} a PERDIDO"]
        } else {
            flash.result = [tipo: 'error', texto: 'Ocurrió un problema al cambiar el estado del paquete.']
        }
        redirect uri:'/'
    }

    def configuracion(Configuracion command) {
        Configuracion config = gestionService.actualizarConfiguracion(command)
        if (!config) {
            flash.result = [tipo: 'error', texto: 'Ocurrió un problema al actualizar la configuración.']
        }
        redirect uri:'/'
    }
}

grails-app/views/componentes/_agregarPaquete.gsp
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Agregar Paquete</h3>
  </div>
  <div class="panel-body">
    <g:form controller="gestion" action="actualizarPaquete">
      <input type="hidden" name="estado" value="PENDIENTE">
      <div class="form-group">
        <input type="number" class="form-control" name="caja" id="caja" placeholder="N° Caja" required>
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="descripcion" id="descripcion" placeholder="Descripción">
      </div>
      <div class="form-group">
        <select id="origen" class="form-control" name="origen.id" required>
          <option value="" disabled selected>Origen</option>
          <g:each in="${ubicaciones}" var="ubicacion">
            <option value="${ubicacion.id}">${ubicacion}</option>
          </g:each>
        </select>
      </div>
      <div class="form-group">
        <select id="destino" class="form-control" name="destino.id" required>
          <option value="" disabled selected>Destino</option>
          <g:each in="${ubicaciones}" var="ubicacion">
            <option value="${ubicacion.id}">${ubicacion}</option>
          </g:each>
        </select>
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary">Preparado</button>
      </div>
    </g:form>
  </div>
</div>

grails-app/views/componentes/_agregarUbicacion.gsp
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Agregar Ubicación</h3>
  </div>
  <div class="panel-body">
    <g:form controller="gestion" action="actualizarUbicacion">
      <div class="form-group">
        <input type="text" class="form-control" name="provincia" placeholder="Provincia" required>
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="localidad" placeholder="Localidad" required>
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="descripcion" placeholder="Descripción">
      </div>
      <div class="text-center">
        <button type="submit" class="btn btn-primary">Agregar</button>
      </div>
    </g:form>
  </div>
</div>

grails-app/views/componentes/_buscarPaquete.gsp
<%@ page import="org.munaylab.lotengo.Estado" %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Buscar Paquete</h3>
  </div>
  <div class="panel-body">
    <g:form controller="gestion" action="buscarPaquete">
      <div class="input-group">
        <input type="number" name="caja" class="form-control" placeholder="N° Caja" required>
        <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </span>
      </div>
    </g:form>
  </div>
</div>

<g:if test="${flash.encontrado}">
  <div class="modal fade" id="encontradoModal" tabindex="-1" role="dialog"
      aria-labelledby="encontradoModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="encontradoModalLabel">
            Paquete N° ${flash.encontrado.paquete.caja} ${flash.encontrado.paquete.estado}
          </h4>
        </div>
        <div class="modal-body">

          <div class="panel panel-default">
            <div class="panel-body">
              <form autocomplete="off">
                <div class="col-sm-3 form-group">
                  <label for="caja">N° Caja</label>
                  <input type="number" class="form-control" id="caja"
                      value="${flash.encontrado.paquete.caja}">
                </div>
                <div class="col-sm-9 form-group">
                  <label for="descripcion">Descripcion</label>
                  <input type="text" class="form-control" id="descripcion"
                      value="${flash.encontrado.paquete.descripcion}">
                </div>
                <div class="col-sm-6 form-group">
                  <label for="origen">Origen</label>
                  <input type="text" class="form-control" id="origen"
                      value="${flash.encontrado.paquete.origen}">
                </div>
                <div class="col-sm-6 form-group">
                  <label for="destino">Destino</label>
                  <input type="text" class="form-control" id="destino"
                      value="${flash.encontrado.paquete.destino}">
                </div>
              </form>
            </div>
            <div class="panel-footer text-right">
              <button type="submit" class="btn btn-primary ">Guardar</button>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Historial</h3>
            </div>
            <div class="panel-body">
              <g:if test="${flash.encontrado.historial}">
                <g:each var="historial" in="${flash.encontrado.historial}">
                  <div class="panel panel-${historial.estado.clase()}">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        Paquete ${historial.estado} el ${historial.fecha.format('dd/MM/yyyy HH:mm')}
                      </h4>
                    </div>
                    <div class="panel-body">
                      <g:if test="${historial.observacion}">
                        <b>Observación:</b>
                        ${historial.observacion}
                      </g:if>
                      <g:else>
                      <div class="text-center">
                        <i>No hay observaciones</i>
                      </div>
                      </g:else>
                    </div>
                  </div>
                </g:each>
              </g:if>
              <g:else>
                <div class="text-center">
                  <i>El paquete está listo para ser enviado</i>
                  <i class="fa fa-check" aria-hidden="true"></i>
                </div>
              </g:else>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(document).ready(function() {
      $('#encontradoModal').modal();
    });
  </script>

</g:if>

grails-app/views/componentes/_configuracion.gsp
<g:set var="config" value="${g.configuracionActual()}" />

<script type="text/javascript">
  $(document).ready(function() {
    $('#config').click(function() {
      $('#configModal').modal();
    });
    $('#configForm input[type=checkbox]').change(function() {
      console.log($(this).attr('name'), $(this).is(':checked'));
      $(this).prop('checked', $(this).is(':checked'));
    });
  });
</script>

<div class="modal fade" id="configModal" tabindex="-1" role="dialog" aria-labelledby="configModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="configModalLabel">Configuración</h4>
      </div>
      <g:form name="configForm" controller="gestion" action="configuracion">
        <input type="hidden" name="id" value="${config.id}">
        <div class="modal-body">
          <div class="row">
            <div class="col-sm-6">
              <div class="checkbox">
                <label>
                  <g:checkBox name="resumen" value="${config.resumen}" /> Panel de resumen
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="buscador" value="${config.buscador}" /> Búsqueda rápida
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="agregarPaquete" value="${config.agregarPaquete}" /> Panel para agregar paquete
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="agregarUbicacion" value="${config.agregarUbicacion}" /> Panel para agregar ubicación
                </label>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="checkbox">
                <label>
                  <g:checkBox name="ultimosMovimientos" value="${config.ultimosMovimientos}" />Listado últimos movimientos
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="paquetesPendientes" value="${config.paquetesPendientes}" /> Listado paquetes pendientes
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="paquetesEnviados" value="${config.paquetesEnviados}" /> Listado paquetes enviados
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="paquetesRecibidos" value="${config.paquetesRecibidos}" /> Listado paquetes recibidos
                </label>
              </div>
              <div class="checkbox">
                <label>
                  <g:checkBox name="paquetesPerdidos" value="${config.paquetesPerdidos}" /> Listado paquetes perdidos
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
      </g:form>
    </div>
  </div>
</div>

grails-app/views/componentes/_confirmarEntrega.gsp
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Confirmar Entrega</h3>
  </div>
  <div class="panel-body">
    <form name="name" action="action">
      <div class="form-group">
        <label for="caja">Caja</label>
        <input type="text" class="form-control" id="caja" placeholder="N° Caja">
      </div>
      <div class="form-group">
        <label for="descripcion">Descripción</label>
        <input type="text" class="form-control" id="descripcion" placeholder="Descripción">
      </div>
      <div class="form-group">
        <label for="observacion">Observación</label>
        <input type="text" class="form-control" id="observacion" placeholder="Observación">
      </div>
      <button type="submit" class="btn btn-default">Enviar</button>
    </form>
  </div>
</div>

grails-app/views/componentes/_enviosCaducados.gsp
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Envíos Caducados</h3>
  </div>
  <div class="panel-body table-responsive">
    <g:if test="${envios}">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>N°</th>
            <th>Envío</th>
            <th>Origen</th>
            <th>Destino</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <g:each in="${envios}" var="envio">
            <tr>
              <td>${envio.paquete.caja}</td>
              <td>Hace ${groovy.time.TimeCategory.minus(new Date(), envio.fecha).days} días</td>
              <td>${envio.paquete.origen}</td>
              <td>${envio.paquete.destino}</td>
              <td>
                <g:form controller="gestion" action="perdido" id="${envio.paquete.id}">
                  <button type="submit" class="btn btn-danger">Perdido</button>
                </g:form>
              </td>
            </tr>
          </g:each>
        </tbody>
      </table>
    </g:if>
    <g:else>
      <div class="text-center">
        <i class="fa fa-table fa-4x" aria-hidden="true"></i>
        <p><i>No se encontraron paquetes pendientes</i></p>
      </div>
    </g:else>
  </div>
</div>

grails-app/views/componentes/_enviosPendientes.gsp
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Entregas Pendientes</h3>
  </div>
  <div class="panel-body table-responsive">
    <g:if test="${envios}">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>N°</th>
            <th>Fecha Envío</th>
            <th>Descripción</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <g:each in="${envios}" var="envio">
            <tr>
              <td>${envio.paquete.caja}</td>
              <td>${envio.fecha.format('dd/MM/yyyy')}</td>
              <td>${envio.paquete.descripcion}</td>
              <td>
                <g:form controller="gestion" action="recibido" id="${envio.paquete.id}">
                  <button type="submit" class="btn btn-primary">Recibido</button>
                </g:form>
              </td>
            </tr>
          </g:each>
        </tbody>
      </table>
    </g:if>
    <g:else>
      <div class="text-center">
        <i class="fa fa-table fa-4x" aria-hidden="true"></i>
        <p><i>No se encontraron paquetes pendientes</i></p>
      </div>
    </g:else>
  </div>
</div>

grails-app/views/componentes/_resumen.gsp
<div class="panel panel-default">
  <div class="panel-body">
    <g:each in="${resumen}" var="registro">
      <div class="alert alert-${registro[1].clase()} text-center" role="alert">
        <h3>
          <i class="fa ${registro[1].icono()}"></i>
          <b>${registro[0]} ${registro[1].toString().toLowerCase().capitalize()}s</b>
        </h3>
      </div>
    </g:each>
  </div>
</div>

grails-app/views/componentes/_ultimosMovimientos.gsp
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Últimos Movimientos</h3>
  </div>
  <div class="panel-body table-responsive">
    <g:if test="${envios}">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>N°</th>
            <th>Acción</th>
            <th>Fecha</th>
            <th>Destino</th>
            <th>Descripción</th>
          </tr>
        </thead>
        <tbody>
          <g:each in="${envios}" var="envio">
            <tr class="${envio.estado.clase()}">
              <td>${envio.paquete.caja}</td>
              <td>${envio.estado}</td>
              <td>${envio.fecha.format('dd/MM/yyyy')}</td>
              <td>${envio.paquete.destino}</td>
              <td>${envio.paquete.descripcion}</td>
              <td>${envio.responsable.username}</td>
            </tr>
          </g:each>
        </tbody>
      </table>
    </g:if>
    <g:else>
      <div class="text-center">
        <i class="fa fa-table fa-4x" aria-hidden="true"></i>
        <p><i>No hay ningún envio para mostrar</i></p>
      </div>
    </g:else>
  </div>
</div>

grails-app/views/componentes/_ultimosPaquetes.gsp
<%@ page import="org.munaylab.lotengo.Estado" %>

<div class="panel panel-${estado.clase()}">
  <div class="panel-heading">
    <h3 class="panel-title">
      <i class="fa ${estado.icono()}" aria-hidden="true"></i>
      Paquetes ${estado.toString().toLowerCase().capitalize()}s
    </h3>
  </div>
  <div class="panel-body table-responsive">
    <g:if test="${paquetes}">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>N°</th>
            <th>Origen</th>
            <th>Destino</th>
            <th>Descripción</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <g:each in="${paquetes}" var="paquete">
            <tr class="${paquete.estado.clase()}">
              <td>${paquete.caja}</td>
              <td>${paquete.origen}</td>
              <td>${paquete.destino}</td>
              <td>${paquete.descripcion}</td>
              <td class="text-right">
                <g:if test="${estado == Estado.PENDIENTE}">
                  <g:form controller="gestion" action="enviar" id="${paquete.id}">
                    <button type="submit" class="btn btn-primary">Enviado</button>
                  </g:form>
                </g:if>
                <g:if test="${estado == Estado.ENVIADO}">
                  <g:form controller="gestion" action="recibido" id="${paquete.id}">
                    <button type="submit" class="btn btn-warning">Recibido</button>
                  </g:form>
                </g:if>
              </td>
            </tr>
          </g:each>
        </tbody>
      </table>
    </g:if>
    <g:else>
      <div class="text-center">
        <i class="fa fa-table fa-4x" aria-hidden="true"></i>
        <p><i>No hay ningún paquete para mostrar</i></p>
      </div>
    </g:else>
  </div>
</div>